import '@/style/main.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="app">
          <main id="app-main">{children}</main>
        </div>
      </body>
    </html>
  );
}
